name: Our Workflow
on:
  push:
    branches: [test]

env:
  WARNING_COLOR: "#FFBF00"
  ERROR_COLOR: "#DF013A"
  SUCCESS_COLOR: "#04B404"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - id: random
        run: exit $(($RANDOM % 2 == 0))
      - id: always
        if: always()
        run: echo ${{steps.random.outcome}}
